# Generated by Django 5.0.4 on 2024-05-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_added',)},
        ),
    ]
