# Generated by Django 5.0.4 on 2024-05-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
    ]
